# Generated by Django 5.2.7 on 2026-01-04 07:03

import ckeditor_uploader.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, choices=[('International', 'International'), ('National', 'National')], max_length=100, null=True)),
                ('district', models.CharField(blank=True, choices=[('Lucknow', 'Lucknow'), ('Bahraich', 'Bahraich'), ('Gonda', 'Gonda'), ('Shravasti-Balrampur', 'Shravasti-Balrampur'), ('Sitapur-Barabanki', 'Sitapur-Barabanki')], max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=350, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mynews.news')),
            ],
        ),
    ]
