# Generated by Django 5.2.7 on 2025-10-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_important', models.BooleanField(default=False)),
            ],
        ),
    ]
