# Generated by Django 5.2.7 on 2026-01-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='url_city',
            field=models.CharField(blank=True, help_text='URL के लिए शहर का नाम (जैसे: New York). खाली छोड़ने पर District का नाम लिया जाएगा।', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('International', 'International'), ('National', 'National'), ('Technology', 'Technology'), ('Bollywood', 'Bollywood')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='district',
            field=models.CharField(blank=True, choices=[('Lucknow-UP', 'Lucknow-UP'), ('UP-National', 'UP-National'), ('Purvanchal', 'Purvanchal'), ('Bahraich-Gonda', 'Bahraich-Gonda'), ('Balrampur-Shravasti', 'Balrampur-Shravasti'), ('Sitapur-Barabanki', 'Sitapur-Barabanki')], max_length=50, null=True),
        ),
    ]
