# Generated by Django 6.0.2 on 2026-03-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='youtube_video_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
