# Generated by Django 5.2.7 on 2026-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_fb_posted',
            field=models.BooleanField(default=False),
        ),
    ]
