# Generated by Django 6.0.2 on 2026-04-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_caption',
        ),
        migrations.AlterField(
            model_name='news',
            name='share_now_to_fb',
            field=models.BooleanField(default=False, verbose_name='Share to FB?'),
        ),
        migrations.AlterField(
            model_name='sidebarwidget',
            name='title',
            field=models.CharField(help_text='पहचान के लिए', max_length=100),
        ),
    ]
