# Generated by Django 6.0.1 on 2026-02-02 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0002_news_is_fb_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Keywords comma se alag karein', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_city',
            field=models.CharField(blank=True, help_text='URL ke liye shehar ka naam. Khali chhodne par District liya jayega.', max_length=100, null=True),
        ),
    ]
