# Generated by Django 6.0.3 on 2026-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0002_news_youtube_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp_news/'),
        ),
    ]
