# Generated by Django 5.2.7 on 2025-10-27 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0002_news_content_news_image_alter_news_youtube_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='headline',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='news',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='Breaking News', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynews.news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='Default news content'),
            preserve_default=False,
        ),
    ]
