# Generated by Django 6.0.1 on 2026-01-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0003_news_image_url_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_pics/', verbose_name='Image'),
        ),
    ]
