# Generated by Django 5.2.7 on 2025-10-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0003_rename_created_at_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_image/'),
        ),
        migrations.AddField(
            model_name='news',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
