# Generated by Django 6.0.1 on 2026-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0003_news_meta_keywords_alter_news_date_alter_news_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='share_now_to_fb',
            field=models.BooleanField(default=False, verbose_name='Facebook par abhi bhejein?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_fb_posted',
            field=models.BooleanField(default=False, verbose_name='FB par post ho chuka hai'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Breaking News?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_city',
            field=models.CharField(blank=True, help_text="Khali chhodne par 'news' liya jayega.", max_length=100, null=True),
        ),
    ]
