# Generated by Django 5.2.7 on 2025-10-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0004_news_image_news_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
