# Generated by Django 5.2.7 on 2026-02-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0004_news_share_now_to_fb_alter_news_is_fb_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='district',
            field=models.CharField(blank=True, choices=[('Int-MiddleEast', 'मिडिल ईस्ट (Middle East)'), ('Int-America', 'अमेरिका (America-Canada)'), ('International', 'अंतर्राष्ट्रीय (International)'), ('Sports', 'खेल जगत (Sports)'), ('Bollywood', 'बॉलीवुड (Bollywood)'), ('Hollywood', 'हॉलीवुड (Hollywood)'), ('Technology', 'टेक्नोलॉजी (Tech)'), ('Market', 'मार्केट / बिज़नेस (Market)'), ('Lucknow-UP', 'लखनऊ न्यूज़'), ('UP-National', 'यूपी राष्ट्रीय'), ('Purvanchal', 'पूर्वांचल'), ('Bahraich-Gonda', 'बहराइच-गोण्डा'), ('Balrampur-Shravasti', 'बलरामपुर-श्रावस्ती'), ('Sitapur-Barabanki', 'सीतापुर-बाराबंकी'), ('Other-States', 'अन्य राज्य (Other States)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_city',
            field=models.CharField(blank=True, help_text="Khali chhodne par 'news' ya district name liya jayega.", max_length=100, null=True),
        ),
    ]
