# Generated by Django 5.2.7 on 2025-10-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0005_news_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='district',
            field=models.CharField(blank=True, choices=[('Lucknow', 'Lucknow'), ('Bahraich', 'Bahraich'), ('Kanpur', 'Kanpur'), ('Varanasi', 'Varanasi')], max_length=100, null=True),
        ),
    ]
