# Generated by Django 5.2.7 on 2025-10-28 16:14

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0007_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mynews.news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='district',
            field=models.CharField(blank=True, choices=[('Lucknow', 'Lucknow'), ('Bahraich', 'Bahraich'), ('Gonda', 'Gonda'), ('Shravasti/Balrampur', 'Shravasti/Balrampur'), ('Sitapur/Barabanki', 'Sitapur/Barabanki')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
