# Generated by Django 5.2.7 on 2025-10-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0008_news_is_important_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('International', 'International'), ('National', 'National')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='district',
            field=models.CharField(blank=True, choices=[('Lucknow', 'Lucknow'), ('Bahraich', 'Bahraich'), ('Gonda', 'Gonda'), ('Shravasti-Balrampur', 'Shravasti-Balrampur'), ('Sitapur-Barabanki', 'Sitapur-Barabanki')], max_length=50, null=True),
        ),
    ]
