# Generated by Django 4.2.7 on 2025-12-14 23:32
from django.db import migrations
from django.utils.text import slugify


def set_unique_slugs(apps, schema_editor):
    """
    Ensures all existing News records have a unique slug before applying the
    unique constraint in the subsequent migration (if any).
    It specifically targets records with null or empty slugs.
    """
    
    News = apps.get_model('mynews', 'News')
    
    
    queryset = News.objects.filter(slug__isnull=True) | News.objects.filter(slug='')

    for news_item in queryset.iterator():
        
        
        base_title = news_item.title if news_item.title else "default-news"
        base_slug = slugify(base_title)

        new_slug = f"{base_slug}-{news_item.pk}"

       
        news_item.slug = new_slug
        news_item.save(update_fields=['slug'])
# -----------------------------

class Migration(migrations.Migration):

    dependencies = [
        
        ('mynews', '0018_alter_news_slug'), 
    ]

    operations = [
        
        migrations.RunPython(set_unique_slugs, migrations.RunPython.noop),

       
    ]