# Generated by Django 5.2.7 on 2025-12-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0018_alter_news_slug'),
        ('mynews', '0020_fake_forward_slug_fix'),
    ]

    operations = [
    ]
