# Generated by Django 5.2.7 on 2025-12-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0021_merge_0018_alter_news_slug_0020_fake_forward_slug_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
