# Generated by Django 6.0.2 on 2026-04-26 18:45

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Market Price (MRP)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Our Selling Price')),
                ('short_description', models.TextField(help_text='Search Result me dikhne ke liye', max_length=500)),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Full Product Details & Review')),
                ('main_image', models.ImageField(upload_to='products/main/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Home Page par dikhayein?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopping.category')),
            ],
        ),
    ]
