# Generated by Django 6.0.2 on 2026-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_now_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Direct Buy Link (External)'),
        ),
    ]
