# Generated by Django 6.0.2 on 2026-04-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_product_buy_now_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('link', models.URLField(blank=True, help_text='स्लाइड पर क्लिक करने पर कहाँ जाना है?', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
