# Generated by Django 6.0.2 on 2026-04-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_alter_category_options_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
