# Generated by Django 6.0.2 on 2026-05-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_alter_category_image_alter_homeslider_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buy_now_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='price_display',
            field=models.CharField(default=0, help_text='जैसे: 500-540 rs', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(help_text='जैसे: Lizi-Bezy, Buy Blue Suit', max_length=150)),
                ('earn_karo_url', models.URLField(help_text='EarnKaro लिंक यहाँ डालें', max_length=700)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='shopping.product')),
            ],
        ),
    ]
