# Generated by Django 6.0.2 on 2026-05-16 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_remove_product_buy_now_url_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlink',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_display',
            field=models.CharField(help_text='जैसे: 1499, 2099', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('earn_karo_url', models.URLField(help_text='इस फोटो के लिए EarnKaro/AJIO लिंक यहाँ डालें', max_length=700)),
                ('variant_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shopping.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductLink',
        ),
    ]
