# Generated by Django on 2026-05-16
from django.db import migrations

def transfer_old_data_to_variants(apps, schema_editor):
    try:
        Product = apps.get_model('shopping', 'Product')
        ProductVariant = apps.get_model('shopping', 'ProductVariant')
        
        # सभी पुराने प्रोडक्ट्स पर लूप चलाएंगे
        for product in Product.objects.all():
            # सुरक्षा कवच: चेक करें कि क्या इस प्रोडक्ट का कोई वेरिएंट पहले से तो नहीं बना है
            if not ProductVariant.objects.filter(product=product).exists():
                
                # हर पुराने प्रोडक्ट के लिए एक डिफ़ॉल्ट वेरिएंट (Variant) ऑटोमैटिक बना रहे हैं
                ProductVariant.objects.create(
                    product=product,
                    variant_code=f"VAR-{product.id}-DEFAULT",
                    # अगर पुराने प्रोडक्ट मॉडल में डायरेक्ट 'image' या 'image_url' था, तो वह यहाँ सुरक्षित आ जाएगा
                    image=getattr(product, 'image', None), 
                    image_url=getattr(product, 'image_url', ''), 
                    earn_karo_url=''  # इसे अभी खाली छोड़ रहे हैं, बाद में एडमिन से बदल सकते हैं
                )
    except Exception as e:
        # अगर कोई पुराना मॉडल पूरी तरह डिलीट हो चुका है और डेटा नहीं मिलता, तो एरर आने के बजाय स्किप हो जाएगा
        print(f"डेटा ट्रांसफर स्क्रिप्ट में रुकावट (स्किप किया गया): {e}")

class Migration(migrations.Migration):

    dependencies = [
        # यह आपकी पिछली 0010 वाली माइग्रेशन फाइल से लिंक हो गया है
        ('shopping', '0010_remove_productlink_product_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer_old_data_to_variants),
    ]