# Generated by Django 6.0.2 on 2026-05-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20260516_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Product का असली MRP यहाँ डालें (जैसे: 1999.00)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_display',
            field=models.CharField(help_text='जैसे: 1499, 2099 (यूजर को दिखाने के लिए स्ट्रिंग)', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='earn_karo_url',
            field=models.URLField(help_text='मास्टर / डिफ़ॉल्ट एफीलिएट लिंक', max_length=700),
        ),
        migrations.CreateModel(
            name='VariantStoreCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(choices=[('AJIO', 'AJIO'), ('MYNTRA', 'Myntra'), ('FLIPKART', 'Flipkart'), ('AMAZON', 'Amazon')], default='AJIO', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Current Selling Price (बिना कूपन के)', max_digits=10)),
                ('coupon_code', models.CharField(blank=True, help_text='जैसे: WISH, SPRING20', max_length=50)),
                ('coupon_discount_value', models.DecimalField(decimal_places=2, default=0.0, help_text='कूपन लगाने पर कितने रुपये कम होंगे', max_digits=10)),
                ('store_affiliate_url', models.URLField(blank=True, help_text='इस स्टोर का विशिष्ट एफीलिएट लिंक', max_length=1000)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='shopping.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Store Coupon',
                'verbose_name_plural': 'Variant Store Coupons',
            },
        ),
    ]
