# Generated by Django 6.0.2 on 2026-05-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_product_mrp_price_alter_product_price_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantstorecoupon',
            name='store_name',
            field=models.CharField(default='Hamaramall', help_text='स्टोर या ब्रांड का नाम सीधे टाइप करें (जैसे: Hamaramall, Libas, Oppo, Mi)', max_length=100),
        ),
    ]
