# Generated by Django 6.0.2 on 2026-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_alter_variantstorecoupon_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(help_text="मेनू का नाम जो वेबसाइट पर दिखेगा (जैसे: Women's Fashion, Men's Fashion)", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='क्या इस मेनू को वेबसाइट पर लाइव दिखाना है?')),
                ('order', models.IntegerField(default=0, help_text='मेनू किस नंबर पर आगे-पीछे दिखेगा (जैसे: 1, 2, 3)')),
                ('categories', models.ManyToManyField(help_text='इस मेनू के अंदर जो-जो कैटेगरीज़ दिखानी हैं, उन्हें सिलेक्ट करें', related_name='dropdown_menus', to='shopping.category')),
            ],
            options={
                'verbose_name': 'Dropdown Menu Manager',
                'verbose_name_plural': 'Dropdown Menu Manager',
                'ordering': ['order', 'menu_name'],
            },
        ),
    ]
