# Generated by Django 6.0.2 on 2026-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_dropdownmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantstorecoupon',
            name='store_affiliate_url',
        ),
        migrations.AlterField(
            model_name='dropdownmenu',
            name='is_active',
            field=models.BooleanField(default=True, help_text='क्या इस Menu को लाइव दिखाना है?'),
        ),
        migrations.AlterField(
            model_name='dropdownmenu',
            name='order',
            field=models.IntegerField(default=0, help_text='मेनू का क्रम नंबर (जैसे: 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_display',
            field=models.CharField(help_text='जैसे: 1499, 500-1500 (यूजर को दिखाने के लिए रेंज या स्ट्रिंग)', max_length=100),
        ),
        migrations.AlterField(
            model_name='variantstorecoupon',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current Selling Price (अनिवार्य नहीं है)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variantstorecoupon',
            name='store_name',
            field=models.CharField(blank=True, default='', help_text='स्टोर या ब्रांड का नाम सीधे टाइप करें (जैसे: Libas, Oppo, Mi)', max_length=100, null=True),
        ),
    ]
