# Generated by Django 6.0.2 on 2026-06-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_remove_variantstorecoupon_store_affiliate_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropdownmenu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variantstorecoupon',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='dropdownmenu',
            name='categories',
            field=models.ManyToManyField(related_name='dropdown_menus', to='shopping.category'),
        ),
        migrations.AlterField(
            model_name='dropdownmenu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dropdownmenu',
            name='menu_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dropdownmenu',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_display',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='earn_karo_url',
            field=models.URLField(max_length=700),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
        migrations.AlterField(
            model_name='variantstorecoupon',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='variantstorecoupon',
            name='coupon_discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variantstorecoupon',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variantstorecoupon',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
