# Generated by Django 6.0.2 on 2026-06-04 18:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_alter_dropdownmenu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='कैटेगरी के बारे में विस्तार से लिखें', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='कीवर्ड्स को कॉमा (,) से अलग करें', null=True),
        ),
    ]
