# Generated by Django 6.0.2 on 2026-06-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_storeconfiguration_alter_category_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreConfiguration',
        ),
        migrations.RemoveField(
            model_name='variantstorecoupon',
            name='coupon_discount_value',
        ),
        migrations.AlterField(
            model_name='variantstorecoupon',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
