# Generated by Django 6.0.2 on 2026-06-07 08:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_delete_storeconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantstorecoupon',
            name='coupon_discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='कैटेगरी के बारे में विस्तार से लिखें', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='कीवर्ड्स को कॉमा (,) से अलग करें', null=True),
        ),
    ]
