# Generated by Django 6.0.2 on 2026-06-08 16:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0020_variantstorecoupon_coupon_discount_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantstorecoupon',
            name='coupon_discount_value',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
