# Generated by Django 6.0.2 on 2026-06-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0022_homesection_homesectionproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesectionproduct',
            name='section',
        ),
        migrations.RemoveField(
            model_name='homesectionproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='HomeSection',
        ),
        migrations.DeleteModel(
            name='HomeSectionProduct',
        ),
    ]
