# Generated by Django 6.0.2 on 2026-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0024_category_meta_description_product_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section_type', models.CharField(choices=[('slider', 'Slider'), ('banner', 'Banner'), ('products', 'Products'), ('categories', 'Categories')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_sections/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='home_sections/mobile/')),
                ('mobile_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='home_category_sections', to='shopping.category')),
                ('products', models.ManyToManyField(blank=True, related_name='home_sections', to='shopping.product')),
            ],
        ),
    ]
