# Generated by Django 6.0.2 on 2026-07-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0025_homesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='link',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='mobile_image',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='mobile_image_url',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='products',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='section_type',
        ),
        migrations.AlterField(
            model_name='homesection',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='home_sections', to='shopping.category'),
        ),
    ]
