# Generated by Django 6.0.2 on 2026-07-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0026_remove_homesection_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesection',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='title',
        ),
        migrations.AddField(
            model_name='homesection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_sections', to='shopping.category'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_sections/'),
        ),
    ]
