# Generated by Django 6.0.2 on 2026-07-05 08:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0027_alter_homesection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('seo_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
