# Generated by Django 6.0.2 on 2026-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0029_pinterestpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLogoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='store_logos/')),
            ],
        ),
    ]
