# Generated by Django 6.0.2 on 2026-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0030_storelogoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelogoupload',
            name='logo',
            field=models.ImageField(upload_to='store_logo/'),
        ),
    ]
