# Generated by Django 6.0.2 on 2026-08-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0032_remove_storelogoupload_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelogoupload',
            name='logo_path',
        ),
        migrations.AddField(
            model_name='storelogoupload',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
    ]
