# Generated by Django 6.0.2 on 2026-08-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0033_remove_storelogoupload_logo_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelogoupload',
            name='logo',
        ),
        migrations.AddField(
            model_name='storelogoupload',
            name='logo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
