# Generated by Django 6.0.2 on 2026-08-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0034_remove_storelogoupload_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('₹', 'INR (₹)'), ('$', 'USD ($)'), ('€', 'EUR (€)')], default='₹', max_length=5),
        ),
    ]
