# Generated by Django 6.0.2 on 2026-08-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0035_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO title for Google India ranking', max_length=255, null=True),
        ),
    ]
