# Generated by Django 6.0.2 on 2026-08-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0036_category_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO title for Google & Bing ranking', max_length=255, null=True),
        ),
    ]
