# Generated by Django 6.0.2 on 2026-09-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0037_alter_category_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
    ]
