# Generated by Django 6.0.2 on 2026-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0039_storeconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='video_url',
            field=models.URLField(blank=True, help_text='Variant-specific showcase video URL', max_length=500, null=True),
        ),
    ]
