# Generated by Django 6.0.2 on 2026-09-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0040_productvariant_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantstorecoupon',
            name='colour',
            field=models.CharField(blank=True, help_text='Colour or specific coupon code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variantstorecoupon',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatically generated short random code slug', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_code',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate, or type your own code', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='variantstorecoupon',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Size or Weight details', max_length=50, null=True),
        ),
    ]
