# Generated by Django 6.0.2 on 2026-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0041_variantstorecoupon_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatically generated short random code slug', unique=True),
        ),
    ]
