# Generated by Django 6.0.2 on 2026-09-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0042_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mrp_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default MRP for all variants if left blank in stores', max_digits=10),
        ),
    ]
