# Generated by Django 6.0.2 on 2026-09-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0043_alter_product_mrp_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_display',
        ),
        migrations.RemoveField(
            model_name='variantstorecoupon',
            name='mrp_price',
        ),
    ]
