# Generated by Django 6.0.2 on 2026-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0044_remove_product_price_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_color',
            field=models.CharField(blank=True, help_text='Default Color if same for all', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_size',
            field=models.CharField(blank=True, help_text='Default Size / Variant Code if same for all', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default Selling Price for all variants', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='store_name',
            field=models.CharField(blank=True, help_text='Store name (e.g., Amazon, Meesho)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Common showcase video URL for this product', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='colour',
            field=models.CharField(blank=True, help_text='Leave blank to use Product Default Color', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use Product Selling Price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default MRP', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='earn_karo_url',
            field=models.URLField(help_text='Affiliate link for this specific variant', max_length=700),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct product image URL from Amazon/Meesho', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_code',
            field=models.CharField(blank=True, help_text='Leave blank to use Product Default Size', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='video_url',
            field=models.URLField(blank=True, help_text='Leave blank to use Product Video URL', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='VariantStoreCoupon',
        ),
    ]
