# Generated by Django 6.0.2 on 2026-09-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0045_product_default_color_product_default_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_code',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MRP Price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, help_text='Size / Weight', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_color',
            field=models.CharField(blank=True, help_text='Default Color', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_size',
            field=models.CharField(blank=True, help_text='Default Size / Weight', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default MRP (Optional)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default Selling Price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='colour',
            field=models.CharField(blank=True, help_text='Colour', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='earn_karo_url',
            field=models.URLField(blank=True, help_text='Affiliate / EarnKaro Link', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image_url',
            field=models.URLField(blank=True, help_text='Variant Image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Variant Selling Price', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='video_url',
            field=models.URLField(blank=True, help_text='Variant Video URL', max_length=500, null=True),
        ),
    ]
