# Generated by Django 6.0.2 on 2026-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0046_remove_product_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='earn_karo_url',
            field=models.URLField(blank=True, help_text='Affiliate / EarnKaro / Amazon Link', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='mrp_price',
            field=models.CharField(blank=True, help_text='MRP Price', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='selling_price',
            field=models.CharField(help_text='Variant Selling Price (e.g., 355 or 355 ~ 390)', max_length=100),
        ),
    ]
